import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: "#f4f7fb",
    },
    header: {
        paddingTop: 52,
        paddingHorizontal: 20,
        paddingBottom: 18,
        backgroundColor: "#14213d",
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
    },
    logo: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: "#ff4d6d",
        alignItems: "center",
        justifyContent: "center",
    },
    logoText: {
        color: "white",
        fontSize: 26,
        fontWeight: "800",
    },
    title: {
        color: "white",
        fontSize: 24,
        fontWeight: "800",
    },
    subtitle: {
        color: "#cbd5e1",
        fontSize: 13,
        marginTop: 2,
    },
    content: {
        padding: 18,
        gap: 18,
        paddingBottom: 40,
    },
    card: {
        backgroundColor: "white",
        borderRadius: 22,
        padding: 16,
        shadowColor: "#0f172a",
        shadowOpacity: 0.08,
        shadowRadius: 16,
        elevation: 3,
    },
    input: {
        minHeight: 120,
        borderWidth: 2,
        borderColor: "#ff4d6d",
        borderRadius: 14,
        padding: 14,
        fontSize: 24,
        textAlignVertical: "top",
        color: "#0f172a",
    },
    actions: {
        flexDirection: "row",
        gap: 8,
        marginTop: 14,
    },
    actionButton: {
        flex: 1,
        backgroundColor: "#14213d",
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: "center",
    },
    disabledButton: {
        backgroundColor: "#d8dee8",
    },
    actionText: {
        color: "white",
        fontWeight: "800",
        textTransform: "uppercase",
        fontSize: 11,
    },
    sectionTitle: {
        marginTop: 22,
        marginBottom: 10,
        fontSize: 18,
        fontWeight: "800",
        color: "#0f172a",
    },
    examples: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
    },
    exampleButton: {
        borderWidth: 1,
        borderColor: "#dbe3ef",
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 12,
        minWidth: "30%",
        alignItems: "center",
        backgroundColor: "#ffffff",
    },
    exampleKana: {
        fontSize: 16,
        fontWeight: "800",
        color: "#0f172a",
    },
    exampleRomaji: {
        fontSize: 12,
        color: "#64748b",
        marginTop: 2,
    },
    keyboardCard: {
        backgroundColor: "white",
        borderRadius: 22,
        padding: 16,
        shadowColor: "#0f172a",
        shadowOpacity: 0.08,
        shadowRadius: 16,
        elevation: 3,
    },
    keyboardTitle: {
        borderWidth: 1,
        borderStyle: "dashed",
        borderColor: "#ff4d6d",
        borderRadius: 12,
        padding: 14,
        marginBottom: 16,
        textTransform: "uppercase",
        letterSpacing: 2,
        fontWeight: "900",
        color: "#14213d",
        fontSize: 16,
    },
    columnLabels: {
        flexDirection: "row",
        gap: 8,
        marginBottom: 6,
        paddingHorizontal: 4,
    },
    columnLabel: {
        flex: 1,
        textAlign: "center",
        color: "#64748b",
        fontSize: 12,
        fontWeight: "700",
    },
    kanaRow: {
        flexDirection: "row",
        gap: 8,
        marginBottom: 8,
    },
    kanaKey: {
        flex: 1,
        minHeight: 62,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#dbe3ef",
        backgroundColor: "#ffffff",
        alignItems: "center",
        justifyContent: "center",
    },
    emptyKey: {
        flex: 1,
        minHeight: 62,
    },
    kana: {
        fontSize: 26,
        color: "#0f172a",
        fontWeight: "800",
    },
    romaji: {
        marginTop: 2,
        color: "#64748b",
        fontSize: 12,
        fontWeight: "700",
    },
});